# = docker compose
# 可以 cd 到 starter/src/main/resources 目录下，事先启动容器，然后启动项目，或者直接启动项目，项目会自动启动容器(但会等待容器启动完成)
# 启动容器中依赖（deploy/docker 目录）：docker compose -p bytedesk -f compose-base.yaml -f compose-db-mysql.yaml -f compose-mq-artemis.yaml -f compose-scenario-standard.yaml up -d
# 停止容器中依赖（deploy/docker 目录）：docker compose -p bytedesk -f compose-base.yaml -f compose-db-mysql.yaml -f compose-mq-artemis.yaml -f compose-scenario-standard.yaml down
#= 跟模块 spring-boot-docker-compose 配合使用
# https://spring.io/guides/topicals/spring-boot-docker
# https://spring.io/blog/2023/06/21/docker-compose-support-in-spring-boot-3-1
# https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-docker-compose
# https://hub.docker.com/r/jackning/bytedesk
# https://springdoc.cn/docker-compose-support-spring-boot/
# https://docs.spring.io/spring-boot/docs/3.2.0/reference/htmlsingle/#features.docker-compose
# ===============================
# true 表示启用 docker compose
# false 表示禁用 docker compose
spring.docker.compose.enabled=false
# 指定 docker compose 文件路径，路径：starter/src/main/resources
# compose 文件统一维护在 deploy/docker，请使用 deploy/docker/start.sh 与 stop.sh 脚本启动
# spring.docker.compose.file=
# 设置Docker Compose项目名称，相当于命令行中的 -p 参数
spring.docker.compose.project-name=bytedesk
