# ===============================
# = Ollama
# ===============================
# 

# ollama: 
# https://docs.spring.io/spring-ai/reference/api/chat/ollama-chat.html
# spring.ai.ollama.init.pull-model-strategy=always
# 默认：11434，为防止本地冲突，如果是docker，需要修改为21434
# spring.ai.ollama.base-url=http://127.0.0.1:11434
spring.ai.ollama.base-url=http://127.0.0.1:21434
spring.ai.ollama.chat.enabled=true
# spring.ai.ollama.chat.options.model=deepseek-r1:latest
spring.ai.ollama.chat.options.model=qwen3:0.6b
spring.ai.ollama.chat.options.temperature=0.7
# spring.ai.ollama.chat.options.numa=false
# https://docs.spring.io/spring-ai/reference/api/embeddings/ollama-embeddings.html
spring.ai.ollama.embedding.enabled=true
# https://github.com/ollama/ollama?tab=readme-ov-file#model-library
spring.ai.ollama.embedding.options.model=bge-m3:latest
# spring.ai.ollama.embedding.options.numa=false
# spring.ai.ollama.init.timeout=60s
# spring.ai.ollama.init.max-retries=2
# https://huggingface.co/BAAI/bge-reranker-v2-m3
spring.ai.ollama.embedding.options.model.rerank=linux6200/bge-reranker-v2-m3:latest
