# ===============================
# = JWT / Features / CORS
# ===============================

# ===============================
# Features config
# ===============================
# enable java ai
bytedesk.features.java-ai=true
# send email by javamail, valid value: javamail/aliyun
bytedesk.features.email-type=javamail
# 头像的访问地址，请修改为服务器实际的地址
bytedesk.features.avatar-base-url=http://127.0.0.1:9003

# ===============================
# CORS config
# ===============================
bytedesk.cors.allowed-origins=*

# ===============================
# JWT config
# ===============================
bytedesk.jwt.secret-key=1dfaf8d004207b628a9a6b859c429f49a9a7ead9fd8161c1e60847aeef06dbd2
# 30 days, milliseconds
bytedesk.jwt.expiration=2592000000
# 60 days, milliseconds
bytedesk.jwt.refresh-token-expiration=5184000000
