# ===============================
# = Elasticsearch / 向量库
# ===============================
#
# ===============================
# = 向量数据库 / Elasticsearch
# ===============================
# https://github.com/spring-projects/spring-ai/blob/main/spring-ai-vector-store/src/main/java/org/springframework/ai/vectorstore/SpringAIVectorStoreTypes.java
# spring.ai.vectorstore.type=none
# spring.ai.vectorstore.type=redis
# spring.ai.vectorstore.type=chroma
spring.ai.vectorstore.type=elasticsearch
# spring.ai.vectorstore.type=weaviate
# spring.ai.vectorstore.type=milvus
# spring.ai.vectorstore.type=pgvector

# elasticsearch
# 浏览器可视化插件管理 es-client: https://gitee.com/q2316367743/es-client
# 配置参数 https://docs.spring.io/spring-ai/reference/api/vectordbs/elasticsearch.html#elasticsearchvector-properties
spring.elasticsearch.uris=http://127.0.0.1:19200
spring.elasticsearch.username=elastic
spring.elasticsearch.password=bytedesk123
# 
spring.ai.vectorstore.elasticsearch.enabled=true
spring.ai.vectorstore.elasticsearch.initialize-schema=true
spring.ai.vectorstore.elasticsearch.index-name=bytedesk_vs_index
spring.ai.vectorstore.elasticsearch.dimensions=1024
# cosine/l2_norm/dot_product
spring.ai.vectorstore.elasticsearch.similarity=cosine
