# ===============================
# = WebSocket/MQTT Socket（含废弃 cluster 配置）
# ===============================

# ===============================
#=com.bytedesk.socket module
# ===============================
# enable socket
bytedesk.socket.enabled=true
# socket host
bytedesk.socket.host=0.0.0.0
# socket port
# bytedesk.socket.port=9883
# websocket port
bytedesk.socket.websocket-port=9885
# leak detector level
bytedesk.socket.leak-detector-level=SIMPLE
# parent event loop group thread count
bytedesk.socket.parent-event-loop-group-thread-count=1
# child event loop group thread count
bytedesk.socket.child-event-loop-group-thread-count=8
# max payload size
bytedesk.socket.max-payload-size=10240

# ===============================
#=废弃 com.bytedesk.cluster module
# ===============================
# enable cluster
# bytedesk.cluster.enabled=false
# cluster nodes
# bytedesk.cluster.nodes=127.0.0.1,127.0.0.2
# bytedesk.cluster.host=230.0.0.0
# bytedesk.cluster.port=6781
# bytedesk.cluster.client-port=6771
