# ===============================
# = 百度翻译
# ===============================
# = 百度翻译
# https://fanyi-api.baidu.com/doc/21
# ===============================
bytedesk.translate.baidu.appid=placeholder
bytedesk.translate.baidu.key=placeholder
