# ===============================
# = Web / Jackson / DevTools
# ===============================
# https://www.cnblogs.com/suizhikuo/p/16997225.html
# spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss.SSSX
spring.jackson.time-zone=GMT+8

# ===============================
#=spring-boot-devtools
# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.devtools
# ===============================
spring.devtools.restart.poll-interval=2s

#
# ===============================

spring.devtools.restart.quiet-period=1s

# ===============================
# = spring-session-data-redis
# https://docs.spring.io/spring-session/reference/guides/boot-redis.html
# ===============================
# server.servlet.session.cookie.name=MY_SESSION_COOKIE
# server.servlet.session.cookie.max-age=3600
# = ai
# ===============================
# spring.mvc.async.request-timeout=10000
