package ai.z.openapi.service.assistant.message.tools.drawing_tool;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * The input string that was used to generate the drawing.
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class AssistantDrawingTool {

	/**
	 * The input string that was used to generate the drawing.
	 */
	@JsonProperty("input")
	private String input;

	/**
	 * A list of outputs generated by the drawing tool.
	 */
	@JsonProperty("outputs")
	private List<AssistantDrawingToolOutput> outputs;

}
