[tool.poetry]
name = "gizmo-agent"
version = "0.1.0"
description = ""
authors = [
    "Lance Martin <lance@langchain.dev>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8.1"
langchain = ">=0.0.333"
openai = ">=0.5.0,<1.0"
anthropic = "^0.3.11"
langchain-experimental = "^0.0.37"
duckduckgo-search = "^3.9.4"
python-magic = "^0.4.27"
bs4 = "^0.0.1"
unstructured = {extras = ["doc", "docx"], version = "^0.10.29"}
pdfminer-six = "^20221105"
wikipedia = "^1.4.0"
boto3 = "^1.28.84"
redis = "^5.0.1"
arxiv = "^2.0.0"
kay = "^0.1.2"
xmltodict = "^0.13.0"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.15"

[tool.langserve]
export_module = "gizmo_agent"
export_attr = "agent_executor"

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
