# Auto-generated by start.sh at 2026-08-27 10:08:26 — do not edit.
# bytedesk 应用数据源/MQ 连接注入（db=mysql, mq=artemis）；显式配置请使用 .env 或环境变量
SPRING_DATASOURCE_URL=jdbc:mysql://bytedesk-mysql:3306/bytedesk?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
SPRING_DATASOURCE_USERNAME=root
SPRING_DATASOURCE_PASSWORD=r8FqfdbWUaN3
BYTEDESK_MQ_TYPE=artemis
BYTEDESK_MQ_RABBITMQ_ENABLED=false
SPRING_ARTEMIS_MODE=embedded
SPRING_ARTEMIS_BROKER_URL=tcp://bytedesk-artemis:61616
SPRING_ARTEMIS_USER=admin
SPRING_ARTEMIS_PASSWORD=admin
SPRING_JMS_CACHE_ENABLED=true
