services:
  bytedesk:
    environment:
      BYTEDESK_MQ_TYPE: rabbitmq
      BYTEDESK_MQ_RABBITMQ_ENABLED: "true"
      SPRING_RABBITMQ_HOST: bytedesk-mq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_DEFAULT_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_DEFAULT_PASS}
      SPRING_RABBITMQ_VIRTUAL_HOST: /
      SPRING_RABBITMQ_CONNECTION_TIMEOUT: 5000
      SPRING_ARTEMIS_MODE: embedded