spring:
  ai:
    dashscope:
      chat:
        enabled: true  # 控制是否启用阿里云百炼相关功能
    vectorstore:
      weaviate:
        enabled: false  # 禁用 Weaviate
      redis:
        enabled: true   # 启用 Redis 