# ===============================
#=默认不起用ai
# ===============================
bytedesk.debug=true
# noai数据库类型：mysql / postgresql / oracle / kingbase / h2
bytedesk.datasource.active=mysql
# 申请实际的license
# https://www.weiyuai.cn/docs/zh-CN/docs/faq#%E9%97%AE%E9%A2%9813%E5%A6%82%E4%BD%95%E8%8E%B7%E5%8F%96%E8%AF%95%E7%94%A8%E7%89%88license
bytedesk.licenseKey=ZjoyMDI2LTA4LTEzOkNPTU1VTklUWToxMC43Ni4zLjEzNDo6Q0RQLVRlc3Q6Rm9yIGRlbW8gcmVzZWFyY2ggYW5kIHZlcmlmaWNhdGlvbjoxNzg0MDA5MTI3:bp/EJyn79vxcodCDb5gKasEhMo1hX0klCkkhIs5Dsn/4g1q0DYyOwO3ZxJ9xVqm7oJbbPrRsTQ9gwXiuxai6ZZ9Q1qnZ4p3u+up6zKs+FjoxNRd+ESmP0k67llizh6VKXiK3HMsBqFDp9XtK3w4/lS5oP1Pl/a73OHAjVtzzOJqYYVnHvw4fqexcNlI3cf0vtvDqo6tAIOx+dVFXkkeVpMkiVTsHo5MGGF/cjbM9Kj2fpNUf+PT56tU9e7gtZIztX/fyCX0ulrsJ6L+68+G09pJZ67sVXPbgGiLn73XKRHnoHS7iGxKH1jekBwYHAct+NxhPV5AGOMrayuYO5Lu8Oph7clln4Mt76Zj3VKSfXfvDMMqMIV0xImS7Jy3alrxSVHkUzaPP7SH9UV3Ap68PJA3deKWmMfYoCjKp0ljBjevo7AzoqxxvXDAFhYTlbXbhd7eOoGgofEnpIW+IzgeAu8+BWuJcHdWphpN/eCDKiDS5u+x0WdE1NH6H5gSnOtd8k3rDhro/YOokggxmcmDmwWB2/SRtRpc57BFsgtpl0CyqpF9oH7AWMDgBJWxClHS8ZTZVGzHTXA09Yp+EqDn/uoI70LdyPB4s0vxv49rqqmCsGcSkM+x4rZ7BxWOAL7waIW6eSm3PSxa8wqzKIQ4BXcBDN3VkoCpU+K5xw1w+WSc=

# ===============================
#= 导入noai环境的配置文件，覆盖默认配置
# ===============================
spring.config.import=\
	optional:classpath:properties/noai/30-core-business.properties,\
	optional:classpath:properties/noai/31-call-freeswitch.properties,\
	optional:classpath:properties/noai/32-webrtc.properties,\
	optional:classpath:properties/noai/33-cache-redis.properties,\
	optional:classpath:properties/noai/40-oauth-ldap-logging.properties,\
	optional:classpath:properties/noai/51-jpa-web-actuator.properties,\
	optional:classpath:properties/noai/60-mq-mail-quartz.properties,\
	optional:classpath:properties/noai/70-ai-batch-liquibase.properties,\
	optional:classpath:properties/noai/75-mcp.properties,\
	optional:classpath:properties/noai/80-flowable.properties,\
	optional:classpath:properties/noai/datasource/50-datasource-common.properties,\
	optional:classpath:properties/noai/datasource/50-datasource-${bytedesk.datasource.active}.properties,\
	optional:classpath:properties/noai/90-thirdparty-cloud.properties,\
	optional:classpath:properties/noai/99-docker-compose.properties
