# ===============================
#=bytedesk
# ===============================
bytedesk.debug=true
bytedesk.version=1.4.5
# open数据库类型：mysql / postgresql / oracle / kingbase / h2
bytedesk.datasource.active=mysql
# 申请实际的license
# https://www.weiyuai.cn/docs/zh-CN/docs/faq#%E9%97%AE%E9%A2%9813%E5%A6%82%E4%BD%95%E8%8E%B7%E5%8F%96%E8%AF%95%E7%94%A8%E7%89%88license
bytedesk.licenseKey=

# ===============================
#= 导入open环境的配置文件，覆盖默认配置
# ===============================
spring.config.import=\
	optional:classpath:properties/open/30-core-business.properties,\
	optional:classpath:properties/open/31-call-freeswitch.properties,\
	optional:classpath:properties/open/40-oauth-ldap-logging.properties,\
	optional:classpath:properties/open/51-jpa-web-actuator.properties,\
	optional:classpath:properties/open/60-mq-mail-quartz.properties,\
	optional:classpath:properties/open/70-ai-batch-liquibase.properties,\
	optional:classpath:properties/open/80-flowable-log.properties,\
	optional:classpath:properties/open/datasource/50-datasource-common.properties,\
	optional:classpath:properties/open/datasource/50-datasource-${bytedesk.datasource.active}.properties,\
	optional:classpath:properties/open/90-thirdparty-cloud.properties,\
	optional:classpath:properties/open/99-docker-compose.properties
