// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Extra;
@class File;
@class Image;
@class Invite;
@class Link;
@class Location;
@class Message;
@class Notice;
@class Preview;
@class Recall;
@class Receipt;
@class Reply;
@class Text;
@class Thread;
@class Transfer;
@class User;
@class Video;
@class Voice;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MessageRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface MessageRoot : GPBRootObject
@end

#pragma mark - Text

typedef GPB_ENUM(Text_FieldNumber) {
  Text_FieldNumber_Content = 1,
};

/**
 * 消息体内容
 **/
GPB_FINAL @interface Text : GPBMessage

/** 文本消息内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@end

#pragma mark - Image

typedef GPB_ENUM(Image_FieldNumber) {
  Image_FieldNumber_MediaId = 1,
  Image_FieldNumber_PicURL = 2,
  Image_FieldNumber_ImageURL = 3,
};

GPB_FINAL @interface Image : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *mediaId;

/** 图片消息, 微信pic_url，web版容易引起跨域访问问题，所以要使用image_url */
@property(nonatomic, readwrite, copy, null_resettable) NSString *picURL;

/** 存储在自己服务器之后的url */
@property(nonatomic, readwrite, copy, null_resettable) NSString *imageURL;

@end

#pragma mark - File

typedef GPB_ENUM(File_FieldNumber) {
  File_FieldNumber_FileURL = 1,
  File_FieldNumber_FileName = 2,
  File_FieldNumber_FileSize = 3,
};

GPB_FINAL @interface File : GPBMessage

/** 文件消息类型，文件url, 文件类型通过format标示 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fileURL;

/** 文件名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fileName;

/** 文件大小 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fileSize;

@end

#pragma mark - Voice

typedef GPB_ENUM(Voice_FieldNumber) {
  Voice_FieldNumber_MediaId = 1,
  Voice_FieldNumber_Format = 2,
  Voice_FieldNumber_VoiceURL = 3,
  Voice_FieldNumber_Length = 4,
  Voice_FieldNumber_Played = 5,
};

GPB_FINAL @interface Voice : GPBMessage

/** 语音消息，图片+语音+视频+短视频 公用字段 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mediaId;

/** 语音格式amr等 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *format;

/** 语音url */
@property(nonatomic, readwrite, copy, null_resettable) NSString *voiceURL;

/**
 * 语音长度
 *    google.protobuf.Int32Value length = 4;
 **/
@property(nonatomic, readwrite) int32_t length;

/** 是否已经播放过 */
@property(nonatomic, readwrite) BOOL played;

@end

#pragma mark - Video

typedef GPB_ENUM(Video_FieldNumber) {
  Video_FieldNumber_MediaId = 1,
  Video_FieldNumber_ThumbMediaId = 2,
  Video_FieldNumber_VideoOrShortURL = 3,
  Video_FieldNumber_VideoOrShortThumbURL = 4,
  Video_FieldNumber_Title = 5,
  Video_FieldNumber_Description_p = 6,
};

GPB_FINAL @interface Video : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *mediaId;

/** 视频和短视频 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *thumbMediaId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *videoOrShortURL;

@property(nonatomic, readwrite, copy, null_resettable) NSString *videoOrShortThumbURL;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

@property(nonatomic, readwrite, copy, null_resettable) NSString *description_p;

@end

#pragma mark - Location

typedef GPB_ENUM(Location_FieldNumber) {
  Location_FieldNumber_LocationX = 1,
  Location_FieldNumber_LocationY = 2,
  Location_FieldNumber_Scale = 3,
  Location_FieldNumber_Label = 4,
};

GPB_FINAL @interface Location : GPBMessage

/** 地理位置消息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *locationX;

@property(nonatomic, readwrite, copy, null_resettable) NSString *locationY;

@property(nonatomic, readwrite, copy, null_resettable) NSString *scale;

@property(nonatomic, readwrite, copy, null_resettable) NSString *label;

@end

#pragma mark - Link

typedef GPB_ENUM(Link_FieldNumber) {
  Link_FieldNumber_Title = 1,
  Link_FieldNumber_Description_p = 2,
  Link_FieldNumber_URL = 3,
};

GPB_FINAL @interface Link : GPBMessage

/** 链接消息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

@property(nonatomic, readwrite, copy, null_resettable) NSString *description_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@end

#pragma mark - Receipt

typedef GPB_ENUM(Receipt_FieldNumber) {
  Receipt_FieldNumber_Mid = 1,
  Receipt_FieldNumber_Status = 2,
};

GPB_FINAL @interface Receipt : GPBMessage

/** 消息回执 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mid;

/** 状态 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *status;

@end

#pragma mark - Reply

typedef GPB_ENUM(Reply_FieldNumber) {
  Reply_FieldNumber_Mid = 1,
  Reply_FieldNumber_Content = 2,
};

GPB_FINAL @interface Reply : GPBMessage

/** 消息回复 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mid;

/** 内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@end

#pragma mark - Preview

typedef GPB_ENUM(Preview_FieldNumber) {
  Preview_FieldNumber_Content = 1,
};

GPB_FINAL @interface Preview : GPBMessage

/** 消息预览 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@end

#pragma mark - Recall

typedef GPB_ENUM(Recall_FieldNumber) {
  Recall_FieldNumber_Mid = 1,
};

GPB_FINAL @interface Recall : GPBMessage

/** 消息撤回 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mid;

@end

#pragma mark - Transfer

typedef GPB_ENUM(Transfer_FieldNumber) {
  Transfer_FieldNumber_Topic = 1,
  Transfer_FieldNumber_Type = 2,
  Transfer_FieldNumber_Content = 3,
  Transfer_FieldNumber_Accept = 4,
};

GPB_FINAL @interface Transfer : GPBMessage

/** 接收者的topic */
@property(nonatomic, readwrite, copy, null_resettable) NSString *topic;

/** 类型：转接会话给 技能组 or 个人 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

/** 附言 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

/** 转接结果：接受 or 拒绝 */
@property(nonatomic, readwrite) BOOL accept;

@end

#pragma mark - Invite

typedef GPB_ENUM(Invite_FieldNumber) {
  Invite_FieldNumber_Topic = 1,
  Invite_FieldNumber_Type = 2,
  Invite_FieldNumber_Content = 3,
  Invite_FieldNumber_Accept = 4,
};

GPB_FINAL @interface Invite : GPBMessage

/** 接收者的topic */
@property(nonatomic, readwrite, copy, null_resettable) NSString *topic;

/** 类型：邀请会话给 技能组 or 个人 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

/** 附言 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

/** 转接结果：接受 or 拒绝 */
@property(nonatomic, readwrite) BOOL accept;

@end

#pragma mark - Notice

typedef GPB_ENUM(Notice_FieldNumber) {
  Notice_FieldNumber_Topic = 1,
  Notice_FieldNumber_Type = 2,
  Notice_FieldNumber_Content = 3,
};

GPB_FINAL @interface Notice : GPBMessage

/** topic */
@property(nonatomic, readwrite, copy, null_resettable) NSString *topic;

/** 会议提醒等 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

/** 内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@end

#pragma mark - Extra

typedef GPB_ENUM(Extra_FieldNumber) {
  Extra_FieldNumber_Content = 1,
};

GPB_FINAL @interface Extra : GPBMessage

/** 开发者自定义字段内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@end

#pragma mark - Message

typedef GPB_ENUM(Message_FieldNumber) {
  Message_FieldNumber_Mid = 1,
  Message_FieldNumber_Status = 3,
  Message_FieldNumber_Timestamp = 4,
  Message_FieldNumber_Client = 6,
  Message_FieldNumber_Version = 7,
  Message_FieldNumber_Type = 8,
  Message_FieldNumber_User = 9,
  Message_FieldNumber_Text = 10,
  Message_FieldNumber_Image = 11,
  Message_FieldNumber_File = 12,
  Message_FieldNumber_Voice = 13,
  Message_FieldNumber_Video = 14,
  Message_FieldNumber_Location = 15,
  Message_FieldNumber_Link = 16,
  Message_FieldNumber_Receipt = 17,
  Message_FieldNumber_Reply = 18,
  Message_FieldNumber_Preview = 19,
  Message_FieldNumber_Recall = 20,
  Message_FieldNumber_Transfer = 21,
  Message_FieldNumber_Invite = 22,
  Message_FieldNumber_Notice = 23,
  Message_FieldNumber_Extra = 30,
  Message_FieldNumber_Thread = 31,
  Message_FieldNumber_Encrypted = 32,
};

typedef GPB_ENUM(Message_Body_OneOfCase) {
  Message_Body_OneOfCase_GPBUnsetOneOfCase = 0,
  Message_Body_OneOfCase_Text = 10,
  Message_Body_OneOfCase_Image = 11,
  Message_Body_OneOfCase_File = 12,
  Message_Body_OneOfCase_Voice = 13,
  Message_Body_OneOfCase_Video = 14,
  Message_Body_OneOfCase_Location = 15,
  Message_Body_OneOfCase_Link = 16,
  Message_Body_OneOfCase_Receipt = 17,
  Message_Body_OneOfCase_Reply = 18,
  Message_Body_OneOfCase_Preview = 19,
  Message_Body_OneOfCase_Recall = 20,
  Message_Body_OneOfCase_Transfer = 21,
  Message_Body_OneOfCase_Invite = 22,
  Message_Body_OneOfCase_Notice = 23,
  Message_Body_OneOfCase_Extra = 30,
};

/**
 * 消息三要素：1. 谁发送的消息？ 2. 发送给谁的消息？ 3. 发送的消息内容是什么？
 **/
GPB_FINAL @interface Message : GPBMessage

/** 唯一ID/localId=mid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mid;

/**
 * 主题：消息接收者为订阅此topic的人
 * string topic = 2;
 * 消息发送状态
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *status;

/**
 * 时间戳
 * string createdAt = 4;
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *timestamp;

/**
 * mqtt clientId
 * string clientId = 5;
 * 消息来源客户端ew
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *client;

/** 消息版本 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *version;

/**
 * 消息类型
 *    MessageType type = 8;
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

/** 1. 谁发送的消息？ 消息发送者 */
@property(nonatomic, readwrite, strong, null_resettable) User *user;
/** Test to see if @c user has been set. */
@property(nonatomic, readwrite) BOOL hasUser;

/** 3. 发送的消息内容是什么？消息体内容，至少设置其中一种 */
@property(nonatomic, readonly) Message_Body_OneOfCase bodyOneOfCase;

@property(nonatomic, readwrite, strong, null_resettable) Text *text;

@property(nonatomic, readwrite, strong, null_resettable) Image *image;

@property(nonatomic, readwrite, strong, null_resettable) File *file;

@property(nonatomic, readwrite, strong, null_resettable) Voice *voice;

@property(nonatomic, readwrite, strong, null_resettable) Video *video;

@property(nonatomic, readwrite, strong, null_resettable) Location *location;

@property(nonatomic, readwrite, strong, null_resettable) Link *link;

@property(nonatomic, readwrite, strong, null_resettable) Receipt *receipt;

@property(nonatomic, readwrite, strong, null_resettable) Reply *reply;

@property(nonatomic, readwrite, strong, null_resettable) Preview *preview;

@property(nonatomic, readwrite, strong, null_resettable) Recall *recall;

@property(nonatomic, readwrite, strong, null_resettable) Transfer *transfer;

@property(nonatomic, readwrite, strong, null_resettable) Invite *invite;

@property(nonatomic, readwrite, strong, null_resettable) Notice *notice;

@property(nonatomic, readwrite, strong, null_resettable) Extra *extra;

/** 2. 发送给谁的消息？客服会话/一对一会话/群组会话 */
@property(nonatomic, readwrite, strong, null_resettable) Thread *thread;
/** Test to see if @c thread has been set. */
@property(nonatomic, readwrite) BOOL hasThread;

/** 是否加密，true为加密，false为明文 */
@property(nonatomic, readwrite) BOOL encrypted;

@end

/**
 * Clears whatever value was set for the oneof 'body'.
 **/
void Message_ClearBodyOneOfCase(Message *message);

#pragma mark - MessageList

typedef GPB_ENUM(MessageList_FieldNumber) {
  MessageList_FieldNumber_ListArray = 1,
};

/**
 * 列表
 **/
GPB_FINAL @interface MessageList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Message*> *listArray;
/** The number of items in @c listArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger listArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
