// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class User;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - UserRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface UserRoot : GPBRootObject
@end

#pragma mark - User

typedef GPB_ENUM(User_FieldNumber) {
  User_FieldNumber_Uid = 1,
  User_FieldNumber_Username = 2,
  User_FieldNumber_Nickname = 3,
  User_FieldNumber_Avatar = 4,
  User_FieldNumber_Client = 5,
  User_FieldNumber_SubDomain = 6,
  User_FieldNumber_Extra = 7,
};

GPB_FINAL @interface User : GPBMessage

/** uuID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

/** 用户名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

/** 昵称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *nickname;

/** 头像 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

/** 来源客户端 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *client;

/** 企业号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *subDomain;

/** 扩展字段 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *extra;

@end

#pragma mark - UserList

typedef GPB_ENUM(UserList_FieldNumber) {
  UserList_FieldNumber_ListArray = 1,
};

/**
 * 列表
 **/
GPB_FINAL @interface UserList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<User*> *listArray;
/** The number of items in @c listArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger listArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
