# ===============================
# = Oracle 配置
# ===============================
spring.datasource.url=jdbc:oracle:thin:@127.0.0.1:11521/FREEPDB1
spring.datasource.username=bytedesk
spring.datasource.password=r8FqfdbWUaN3
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.oracle.OracleDelegate
spring.quartz.jdbc.platform=oracle
spring.batch.jdbc.platform=oracle
spring.batch.database-type=ORACLE
flowable.database-type=oracle

# ===============================
# = Oracle 主从读写分离（可选）
# ===============================
# bytedesk.datasource.oracle-replication.enabled=false
# bytedesk.datasource.oracle-replication.read-only-route-enabled=true
# bytedesk.datasource.oracle-replication.read-balance=round-robin
# bytedesk.datasource.oracle.master.url=jdbc:oracle:thin:@127.0.0.1:11521/FREEPDB1
# bytedesk.datasource.oracle.master.username=bytedesk
# bytedesk.datasource.oracle.master.password=ENC(xxx)
# bytedesk.datasource.oracle.master.driver-class-name=oracle.jdbc.OracleDriver
# bytedesk.datasource.oracle.replicas[0].url=jdbc:oracle:thin:@127.0.0.1:21521/FREEPDB1
# bytedesk.datasource.oracle.replicas[0].username=bytedesk
# bytedesk.datasource.oracle.replicas[0].password=ENC(xxx)
# bytedesk.datasource.oracle.replicas[0].driver-class-name=oracle.jdbc.OracleDriver
