# ===============================
# = Kingbase 配置
# ===============================
spring.datasource.url=jdbc:kingbase8://127.0.0.1:54321/bytedesk?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
spring.datasource.username=root
spring.datasource.password=r8FqfdbWUaN3
spring.datasource.driver-class-name=com.kingbase8.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
spring.quartz.jdbc.platform=postgres
spring.batch.jdbc.platform=postgres
spring.batch.database-type=POSTGRES
flowable.database-type=postgres
spring.liquibase.enabled=false
