# ===============================
# = MySQL 配置（默认）
# ===============================
spring.datasource.url=jdbc:mysql://127.0.0.1:13306/bytedesk?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
spring.datasource.username=root
spring.datasource.password=r8FqfdbWUaN3
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database=mysql
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.StdJDBCDelegate
spring.quartz.jdbc.platform=mysql
spring.batch.jdbc.platform=mysql
spring.batch.database-type=MYSQL
flowable.database-type=mysql

# ===============================
# = MySQL 主从读写分离（可选）
# ===============================
# bytedesk.datasource.mysql-replication.enabled=false
# bytedesk.datasource.mysql-replication.read-only-route-enabled=true
# bytedesk.datasource.mysql-replication.read-balance=round-robin
# bytedesk.datasource.master.url=jdbc:mysql://127.0.0.1:13306/bytedesk?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
# bytedesk.datasource.master.username=root
# bytedesk.datasource.master.password=ENC(xxx)
# bytedesk.datasource.master.driver-class-name=com.mysql.cj.jdbc.Driver
# bytedesk.datasource.replicas[0].url=jdbc:mysql://127.0.0.1:23306/bytedesk?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
# bytedesk.datasource.replicas[0].username=root
# bytedesk.datasource.replicas[0].password=ENC(xxx)
# bytedesk.datasource.replicas[0].driver-class-name=com.mysql.cj.jdbc.Driver
