# ===============================
# = PostgreSQL 配置
# ===============================
spring.datasource.url=jdbc:postgresql://127.0.0.1:15432/bytedesk
spring.datasource.username=postgres
spring.datasource.password=r8FqfdbWUaN3
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
spring.quartz.jdbc.platform=postgres
spring.batch.jdbc.platform=postgres
spring.batch.database-type=POSTGRES
flowable.database-type=postgres

# ===============================
# = PostgreSQL 主从读写分离（可选）
# ===============================
# bytedesk.datasource.postgresql-replication.enabled=false
# bytedesk.datasource.postgresql-replication.read-only-route-enabled=true
# bytedesk.datasource.postgresql-replication.read-balance=round-robin
# bytedesk.datasource.postgresql.master.url=jdbc:postgresql://127.0.0.1:15432/bytedesk
# bytedesk.datasource.postgresql.master.username=postgres
# bytedesk.datasource.postgresql.master.password=ENC(xxx)
# bytedesk.datasource.postgresql.master.driver-class-name=org.postgresql.Driver
# bytedesk.datasource.postgresql.replicas[0].url=jdbc:postgresql://127.0.0.1:25432/bytedesk
# bytedesk.datasource.postgresql.replicas[0].username=postgres
# bytedesk.datasource.postgresql.replicas[0].password=ENC(xxx)
# bytedesk.datasource.postgresql.replicas[0].driver-class-name=org.postgresql.Driver
