services:
  bytedesk-db:
    image: mysql:latest
    container_name: mysql-bytedesk
    environment:
      MYSQL_DATABASE: bytedesk
      MYSQL_ROOT_PASSWORD: r8FqfdbWUaN3
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-time-zone=+8:00
    ports:
      - "3306:3306"
  bytedesk-redis:
    image: redis/redis-stack-server:latest
    container_name: redis-bytedesk
    environment:
      - REDIS_ARGS=--requirepass qfRxz3tVT8Nh
    ports:
      - "6379:6379"
