# ===============================
# = Spring AI 模型选择
# ===============================

# 文本对话配置
# https://www.weiyuai.cn/docs/zh-CN/docs/provider/model_text
spring.ai.model.chat=none
# spring.ai.model.chat=ollama
# spring.ai.model.chat=zhipuai
# spring.ai.model.chat=dashscope

# 向量模型
# https://www.weiyuai.cn/docs/zh-CN/docs/provider/model_embedding
spring.ai.model.embedding=none
# spring.ai.model.embedding=ollama
# spring.ai.model.embedding=zhipuai
# spring.ai.model.embedding=dashscope
# spring.ai.model.embedding.text=
# spring.ai.model.embedding.multimodal=

# 视觉模型
# https://www.weiyuai.cn/docs/zh-CN/docs/provider/model_vision
spring.ai.model.vision=none
# spring.ai.model.vision=ollama
# spring.ai.model.vision=zhipuai
# spring.ai.model.vision=dashscope
# 
spring.ai.model.image=none
spring.ai.model.moderation=none

# 语音模型
spring.ai.model.audio=none
# spring.ai.model.audio=ollama
# spring.ai.model.audio=zhipuai
# spring.ai.model.audio=dashscope
# 
spring.ai.model.audio.speech=none
spring.ai.model.audio.transcription=none

# 重排序模型
spring.ai.model.rerank=none
# spring.ai.model.rerank=ollama
# spring.ai.model.rerank=zhipuai
# spring.ai.model.rerank=dashscope

# 多模态模型
spring.ai.model.multimodal=none
# spring.ai.model.multimodal=ollama
# spring.ai.model.multimodal=zhipuai
# spring.ai.model.multimodal=dashscope
