# ===============================
# = 其他 AI 厂商模板（默认注释，按需启用）
# ===============================
# spring.ai.nacos.prompt.template.enabled=false

# https://docs.spring.io/spring-ai/reference/api/vectordbs/pgvector.html#pgvector-properties
# spring.ai.vectorstore.pgvector.index-type=HNSW
# spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
# spring.ai.vectorstore.pgvector.dimensions=1024
# 
# https://docs.spring.io/spring-ai/reference/api/vectordbs/redis.html
# spring.ai.vectorstore.redis.enabled=true
# spring.ai.vectorstore.redis.initialize-schema=true
# spring.ai.vectorstore.redis.uri=redis://127.0.0.1:6379
# spring.ai.vectorstore.redis.index-name=bytedesk_vs_index
# spring.ai.vectorstore.redis.prefix=bytedesk_vs_prefix:
# spring.ai.vectorstore.redis.batching-strategy=TOKEN_COUNT # Optional: Controls how documents are batched for embedding
