# ===============================
# = 组织 / 成员 / 坐席
# ===============================

# ===============================
#= Member config
# ===============================
# create/import member default password
bytedesk.member.password=123456

# ===============================
# Organization config
# ===============================
# organization name
bytedesk.organization.name=MyCompany
# organization code
bytedesk.organization.code=bytedesk

# when user has no organization after login, whether UI allows creating/joining an organization
# default true/true
bytedesk.organization.allow-create-org=true
bytedesk.organization.allow-join-org=true
# default vip level for new organizations
bytedesk.organization.default-vip-level=0
# default validity (days) for new organizations
bytedesk.organization.default-vip-days=365
# default limits for new organizations
bytedesk.organization.default-max-members=20
bytedesk.organization.default-max-agents=20
bytedesk.organization.default-max-workgroups=20

# ===============================
# service config
# ===============================
bytedesk.service.agent-seat-enabled=false
