# ===============================
# = APNs 推送
# ===============================

# ===============================
#= push 
# ===============================
# apns bundle id
bytedesk.push.apns.bundle-id=com.kefux.im
# apns p12 url
bytedesk.push.apns.p12-url=123.p12
# apns p12 password
bytedesk.push.apns.p12-password=123456
