# ===============================
# = springdoc-openapi / knife4j
# ===============================

# ===============================
#=springdoc
# https://springdoc.org/#properties
# http://127.0.0.1:9003/swagger-ui/index.html
# http://127.0.0.1:9003/v3/api-docs
# ===============================
springdoc.show-actuator=false
# swagger-ui
# http://127.0.0.1:9003/swagger-ui/index.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger.html
# api-docs
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
# knife4j
#  http://127.0.0.1:9003/doc.html
knife4j.enabled=true
knife4j.setting.language=zh_cn
