package ai.z.openapi.service.assistant.message.tools.function;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.JsonNode;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * This class represents a function tool with a name, arguments, and outputs.
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class AssistantFunctionTool {

	/**
	 * The name of the function tool.
	 */
	@JsonProperty("name")
	private String name;

	/**
	 * The arguments for the function tool, which can be a string or a dictionary.
	 */
	@JsonProperty("arguments")
	private JsonNode arguments;

	/**
	 * A list of outputs generated by the function tool.
	 */
	@JsonProperty("outputs")
	private List<AssistantFunctionToolOutput> outputs;

}
