bytedesk:
  voc:
    # 反馈配置
    max-feedback-length: 5000
    max-reply-length: 1000
    max-replies-per-feedback: 100
    
    # 通知配置
    email-notification: true
    notification-email: voc@bytedesk.com
    admin-emails:
      - admin@bytedesk.com
      
    # 审核配置  
    require-approval: false
    filter-sensitive-words: true
    sensitive-words-file: sensitive-words.txt
    
spring:
  mail:
    host: smtp.example.com
    port: 587
    username: noreply@bytedesk.com
    password: your-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true 