# ===============================
# = H2 配置（开发测试）
# ===============================
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
# spring.h2.console.settings.trace=false
# spring.h2.console.settings.web-allow-others=false

spring.datasource.url=jdbc:h2:file:./h2db/weiyuim
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.StdJDBCDelegate
spring.quartz.jdbc.platform=h2
spring.batch.jdbc.platform=h2
spring.batch.database-type=H2
flowable.database-type=h2
