# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# 
# github：依次添加以下变量，
# 路径：Settings -> Secrets And Variables -> Actions
# SERVER_HOST / Secret：服务器公网IP
# SERVER_USERNAME / Secret：服务器用户名
# SERVER_PASSWORD / Secret：服务器密码
# SERVER_PORT / Secret：服务器端口

name: cicd
on:
  push:
    branches: main
    # 打标签的时候触发
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest # 运行环境
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      # https://github.com/actions/setup-java
      - name: install JDK17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      # https://github.com/arduino/setup-protoc
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      # 直接本地打包好jar包，然后上传到服务器？
      - name: Maven build
        run: |
          mvn clean
          mvn -B -DskipTests=true install --file pom.xml
          cd starter 
          mvn -B -DskipTests=true package --file pom.xml
      # https://github.com/OswaldAKs/CICD-Pipeline-with-GithubActions-Docker
      # https://github.com/docker/login-action
      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:latest
      - name: Create and use a new builder
        run: |
          docker buildx create --use --name mybuilder
          docker buildx inspect mybuilder --bootstrap
      # https://github.com/docker/build-push-action
      - name: push the docker image to docker hub
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/bytedesk:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7,windows/amd64,windows/arm64,macos/amd64,macos/arm64
      # 登录阿里云 Docker
      - name: login to aliyun docker
        run: echo ${{ secrets.ALIYUN_DOCKER_PASSWORD }} | docker login --username ${{ secrets.ALIYUN_DOCKER_USERNAME }} --password-stdin registry.cn-hangzhou.aliyuncs.com
      # 构建并推送 Docker 镜像到阿里云
      - name: Build and push Docker image to Aliyun
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/weiyuai/bytedesk:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7,windows/amd64,windows/arm64,macos/amd64,macos/arm64